apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc3
  namespace: dept-1
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: mongodb-pv

